### ISSUE TITLE
Toggle to generate the key in PKCS#8 format

### ISSUE THREAD

**Issue by mikn** [proofpoint/certificate-init-container#10]
The PKCS#8 format is widely supported (java and most applications implementing TLS through any library can use it). I think it is a good alternative to supporting keystore format for java support. It could be controlled by a flag and be output to the same filename as the original PKCS#1 key.
Could also support encryption of the key then, though that may be a bit redundant in an automated system (other than for compliance reasons).

**Comment by johngmyers** [comment]
Why not use the jks format already written by certificate-init-container?

Encryption of the key is simply not useful as the POD has to have the password readily available in order to use it. This is why the jks support uses a fixed password.

**Comment by mikn** [comment]
Again, pretty poorly worded. I did not properly read the code before filing it, but I see you have stripped out storing in PKCS#1 format - we however require PEM formatted keys for some of our non-java projects. What I'd like is support for PKCS#8 key format to support non-Java projects :)
(I implemented PKCS#8 format to cover both my java and non-java apps, hence the half-baked issue)

**Comment by johngmyers** [comment]
The code writes out both PEM and JKS format. The PEM code is in certreq.go.

Do you have projects that require PCKS#8 instead of either PEM or JKS?

**Comment by mikn** [comment]
Oh. I must have missed that! No, I do not think so. I guess in the end, I would prefer not to write out multiple formats at once, but this will work ok for us.

**Comment by johngmyers** [comment]
I see always writing multiple formats as being much cheaper than making the deployment author  specify which format is needed.

Are you okay with closing this then?

**Comment by mikn** [comment]
Sure.
