### ISSUE TITLE
Automatically Approve

### ISSUE THREAD

**Issue by mornindew** [proofpoint/certificate-init-container#20]
Not sure if this is the best place for this but I am using your container and it is working great!  Thank you for that.

Currrently I have to manually approve the CSR (kubectl certificate approve <csr name>).  I want my pipeline (jenkins) to automatically approve them as part of the deploy.   Is there a recommended way to do this?

**Comment by johngmyers** [comment]
Take a look at proofpoint/kapprover, as mentioned in the README.

**Comment by mornindew** [comment]
Sorry, should have noticed that.   Thank you.
