### ISSUE TITLE
When certificate and key is stored in secret, do not write to disk

### ISSUE THREAD

**Issue by mikn** [proofpoint/certificate-init-container#9]
Use case: We run a job to initialize an index for Searchguard in Elasticsearch that authenticates using a client certificate to our cluster. This requires an "admin" client certificate that has a DN that is matched on. We store this in a secret right now to allow users to use it to manually administer the Searchguard index, and then mount the secret in the main container. So there is no need to write it to disk.

For us specifically, there's no need for the manual workflow however, so if there's an automatic approver, we can use transient keys instead.

**Comment by johngmyers** [comment]
* What is the disadvantage of also writing it to disk? Is it worth the complexity of adding an option to not write to disk?

* So the desire is to allow a human to easily fish out the credential for a pod and then manually act using the pod's identity? Would it be too expensive to set up a separate approval path to allow humans to get appropriate credentials in their own right? The latter would be better for audit logs.

**Comment by mikn** [comment]
I agree with you, it would be better for humans to get their keys in a separate process, so maybe it is a feature you can strip completely?
What I was very clumsily getting to in the end was that if you choose to store in a secret, you should only store in a secret - as then you can check whether the secret exists and exit if it does, making a very simple implementation (rather than also reading it out and writing to disk).

**Comment by johngmyers** [comment]
I was wondering whether I should rip that back out. It wasn't, however, getting in the way and I considered that, despite my not being able to figure out the use case, there must have been one for Onedata to have written that code.

If the secret exists, I don't know why the value in it would necessarily be better than the one just issued. I would think the value in the secret would be more likely to be nearing or past expiration, have an out-of-date set of SANs, etc.

**Comment by mikn** [comment]
That is true. Perhaps it can be stripped out? I can honestly not think of a case where you'd want to have an automatically approved key/cert pair in a secret.

**Comment by johngmyers** [comment]
Removed support for writing to a secret.
